//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class dangky
    {
        public int id { get; set; }
        public int maSoKhachHang { get; set; }
        public int maTour { get; set; }
        public System.DateTime ngayDangKy { get; set; }
        public int maSoDoan { get; set; }
        public Nullable<int> soLuongKhachHang { get; set; }
        public Nullable<double> giaTourDangKy { get; set; }
        public int trangThai { get; set; }
    }
}
