//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class doandulich
    {
        public int maSoDoan { get; set; }
        public string tenGoiDoan { get; set; }
        public int soLuongKhachHang { get; set; }
        public int SoLuongNhanVien { get; set; }
        public System.DateTime thoiGianKhoiHanh { get; set; }
        public System.DateTime thoiGianKetThuc { get; set; }
        public string chiTiet { get; set; }
        public int maSoTour { get; set; }
        public int trangThai { get; set; }
    }
}
