//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class giatour
    {
        public int id { get; set; }
        public int maGiaTour { get; set; }
        public double gia { get; set; }
        public string dieuKien { get; set; }
    }
}
