//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public int maSoKhachHang { get; set; }
        public string hoTenKhachHang { get; set; }
        public string soCMND { get; set; }
        public string diaChi { get; set; }
        public string gioiTinh { get; set; }
        public string SDT { get; set; }
        public string quocTich { get; set; }
        public int trangThai { get; set; }
    }
}
