//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourdulichEntities : DbContext
    {
        public tourdulichEntities()
            : base("name=tourdulichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chiphi> chiphis { get; set; }
        public virtual DbSet<dangky> dangkies { get; set; }
        public virtual DbSet<diadiemden> diadiemdens { get; set; }
        public virtual DbSet<diadiemthamquan> diadiemthamquans { get; set; }
        public virtual DbSet<diadiemtour> diadiemtours { get; set; }
        public virtual DbSet<doandulich> doanduliches { get; set; }
        public virtual DbSet<giatour> giatours { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaihinhdulich> loaihinhduliches { get; set; }
        public virtual DbSet<loaikhachhang> loaikhachhangs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<thamgiadoan> thamgiadoans { get; set; }
        public virtual DbSet<tour> tours { get; set; }
    }
}
