//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public int maNhanVien { get; set; }
        public string tenNhanVien { get; set; }
        public string nhiemVu { get; set; }
        public int trangThai { get; set; }
    }
}
