//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public int maSoTour { get; set; }
        public string tenGoiTour { get; set; }
        public string dacDiem { get; set; }
        public int maLoaiHinhDuLich { get; set; }
        public int soLuongKhachHang { get; set; }
        public double tongTien { get; set; }
        public System.DateTime thoiGianBatDau { get; set; }
        public System.DateTime thoiGianKetThuc { get; set; }
        public Nullable<int> maDiaDiemDen { get; set; }
        public Nullable<int> idGiaTour { get; set; }
    }
}
