//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiphi
    {
        public int maChiPhi { get; set; }
        public double tongChiPhi { get; set; }
        public int maSoDoan { get; set; }
        public int maLoaiChiPhi { get; set; }
    }
}
