//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class diadiemthamquan
    {
        public int maDiaDiem { get; set; }
        public string tenDiaDiem { get; set; }
        public Nullable<int> maDiaDiemDen { get; set; }
    }
}
